In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [2]:
#Training Models on Basic Data
df=pd.read_csv("Datasets/cleandata.csv")
df.drop(df.columns[0],axis=1,inplace=True)
df.head()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       1              0        1           0       1             0   
1       0              0        0           0      34             1   
2       0              0        0           0       2             1   
3       0              0        0           0      45             0   
4       1              0        0           0       2             1   

   MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0              2                1               0             1   
1              0                1               1             0   
2              0                1               1             1   
3              2                1               1             0   
4              0                2               0             0   

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                 0            0            0                0         0   
1                 1            0            0                0         1   
2                 0            0            0                0         0   
3                 1            1            0                0         1   
4                 0            0            0                0         0   

   PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0                 1              0           29.85         29.85      0  
1                 0              1           56.95       1889.50      0  
2                 1              1           53.85        108.15      1  
3                 0              2           42.30       1840.75      0  
4                 1              0           70.70        151.65      1

In [3]:
#prepare Data for training/testing
X=df.iloc[:,:-1]
y=df.iloc[:,-1]


In [4]:
X.shape

(7043, 19)

In [5]:
y.shape

(7043,)

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=21)

In [7]:
#KNN Model
knn=KNeighborsClassifier(n_neighbors=20)
knn.fit(X_train,y_train)
yknn=knn.predict(X_test)
knnacc=accuracy_score(yknn,y_test)
knnmatrix=confusion_matrix(y_test,yknn)
knnreport=classification_report(y_test,yknn,output_dict=True)
print(knnacc)
print(knnmatrix)
print(knnreport)

0.7920511000709723
[[983  52]
 [241 133]]
{'0': {'precision': 0.8031045751633987, 'recall': 0.9497584541062802, 'f1-score': 0.8702965914121292, 'support': 1035.0}, '1': {'precision': 0.7189189189189189, 'recall': 0.35561497326203206, 'f1-score': 0.47584973166368516, 'support': 374.0}, 'accuracy': 0.7920511000709723, 'macro avg': {'precision': 0.7610117470411588, 'recall': 0.6526867136841561, 'f1-score': 0.6730731615379072, 'support': 1409.0}, 'weighted avg': {'precision': 0.7807586309224934, 'recall': 0.7920511000709723, 'f1-score': 0.765596005503032, 'support': 1409.0}}


In [8]:
#SVC model
svc=SVC()
svc.fit(X_train,y_train)
ysvc=svc.predict(X_test)
svcacc=accuracy_score(ysvc,y_test)
svcmatrix=confusion_matrix(y_test,ysvc)
svcreport=classification_report(y_test,ysvc,output_dict=True)
print(svcacc)
print(svcmatrix)
print(svcreport)

0.7345635202271115
[[1035    0]
 [ 374    0]]
{'0': {'precision': 0.7345635202271115, 'recall': 1.0, 'f1-score': 0.8469721767594108, 'support': 1035.0}, '1': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 374.0}, 'accuracy': 0.7345635202271115, 'macro avg': {'precision': 0.36728176011355573, 'recall': 0.5, 'f1-score': 0.4234860883797054, 'support': 1409.0}, 'weighted avg': {'precision': 0.539583565248446, 'recall': 0.7345635202271115, 'f1-score': 0.6221548636948121, 'support': 1409.0}}


d:\ClassificationProject\.venv\lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\ClassificationProject\.venv\lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
d:\ClassificationProject\.venv\lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [9]:
#Logistic Regression Model
logreg=LogisticRegression(max_iter=1000)
logreg.fit(X_train,y_train)
ylogreg=logreg.predict(X_test)
logregacc=accuracy_score(ylogreg,y_test)
logregmatrix=confusion_matrix(y_test,ylogreg)
logregreport=classification_report(y_test,ylogreg,output_dict=True)
print(logregacc)
print(logregmatrix)
print(logregreport)

0.794889992902768
[[918 117]
 [172 202]]
{'0': {'precision': 0.8422018348623853, 'recall': 0.8869565217391304, 'f1-score': 0.864, 'support': 1035.0}, '1': {'precision': 0.6332288401253918, 'recall': 0.5401069518716578, 'f1-score': 0.5829725829725829, 'support': 374.0}, 'accuracy': 0.794889992902768, 'macro avg': {'precision': 0.7377153374938885, 'recall': 0.7135317368053942, 'f1-score': 0.7234862914862914, 'support': 1409.0}, 'weighted avg': {'precision': 0.7867327787717995, 'recall': 0.794889992902768, 'f1-score': 0.7894050717045749, 'support': 1409.0}}


d:\ClassificationProject\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [10]:
#Tree Model
tree=DecisionTreeClassifier()
tree.fit(X_train,y_train)
ytree=tree.predict(X_test)
treeacc=accuracy_score(ytree,y_test)
treematrix=confusion_matrix(y_test,ytree)
treereport=classification_report(y_test,ytree,output_dict=True)
print(treeacc)
print(treematrix)
print(treereport)

0.7239176721078779
[[837 198]
 [191 183]]
{'0': {'precision': 0.8142023346303502, 'recall': 0.808695652173913, 'f1-score': 0.8114396509936985, 'support': 1035.0}, '1': {'precision': 0.48031496062992124, 'recall': 0.4893048128342246, 'f1-score': 0.4847682119205298, 'support': 374.0}, 'accuracy': 0.7239176721078779, 'macro avg': {'precision': 0.6472586476301357, 'recall': 0.6490002325040688, 'f1-score': 0.6481039314571142, 'support': 1409.0}, 'weighted avg': {'precision': 0.7255764454350624, 'recall': 0.7239176721078779, 'f1-score': 0.724729134163773, 'support': 1409.0}}


In [11]:
#Forest Model
forest=RandomForestClassifier()
forest.fit(X_train,y_train)
yforest=forest.predict(X_test)
forestacc=accuracy_score(yforest,y_test)
forestmatrix=confusion_matrix(y_test,yforest)
forestreport=classification_report(y_test,yforest,output_dict=True)
print(forestacc)
print(forestmatrix)
print(forestreport)

0.7863733144073811
[[937  98]
 [203 171]]
{'0': {'precision': 0.8219298245614035, 'recall': 0.9053140096618357, 'f1-score': 0.8616091954022989, 'support': 1035.0}, '1': {'precision': 0.6356877323420075, 'recall': 0.4572192513368984, 'f1-score': 0.5318818040435459, 'support': 374.0}, 'accuracy': 0.7863733144073811, 'macro avg': {'precision': 0.7288087784517054, 'recall': 0.6812666304993671, 'f1-score': 0.6967454997229223, 'support': 1409.0}, 'weighted avg': {'precision': 0.7724943792171493, 'recall': 0.7863733144073811, 'f1-score': 0.774087517355334, 'support': 1409.0}}


In [12]:
pd.DataFrame(treereport).head()

0           1  accuracy    macro avg  weighted avg
precision     0.814202    0.480315  0.723918     0.647259      0.725576
recall        0.808696    0.489305  0.723918     0.649000      0.723918
f1-score      0.811440    0.484768  0.723918     0.648104      0.724729
support    1035.000000  374.000000  0.723918  1409.000000   1409.000000

In [29]:
metrics={
    "model":["baseknn","basesvc","baseLogReg","baseTree","baseForest"],
    "precision":[knnreport["weighted avg"]["precision"],svcreport["weighted avg"]["precision"],logregreport["weighted avg"]["precision"],treereport["weighted avg"]["precision"],forestreport["weighted avg"]["precision"]],
    "recall":[knnreport["weighted avg"]["recall"],svcreport["weighted avg"]["recall"],logregreport["weighted avg"]["recall"],treereport["weighted avg"]["recall"],forestreport["weighted avg"]["recall"]],
    "f1":[knnreport["weighted avg"]['f1-score'],svcreport["weighted avg"]["f1-score"],logregreport["weighted avg"]["f1-score"],treereport["weighted avg"]["f1-score"],forestreport["weighted avg"]["f1-score"]]
}
metrics=pd.DataFrame(metrics)
metrics.head()

model  precision    recall        f1
0     baseknn   0.780759  0.792051  0.765596
1     basesvc   0.539584  0.734564  0.622155
2  baseLogReg   0.786733  0.794890  0.789405
3    baseTree   0.725576  0.723918  0.724729
4  baseForest   0.772494  0.786373  0.774088

In [30]:
metrics.to_csv("Metrics.csv")