In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [2]:
#Training Models on Basic Data
df=pd.read_csv("Datasets/normaldata.csv")
df.drop(df.columns[0],axis=1,inplace=True)
df.head()

gender  SeniorCitizen  Partner  Dependents    tenure  PhoneService  \
0     1.0            0.0      1.0         0.0  0.013889           0.0   
1     0.0            0.0      0.0         0.0  0.472222           1.0   
2     0.0            0.0      0.0         0.0  0.027778           1.0   
3     0.0            0.0      0.0         0.0  0.625000           0.0   
4     1.0            0.0      0.0         0.0  0.027778           1.0   

   MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0            1.0              0.5             0.0           0.5   
1            0.0              0.5             0.5           0.0   
2            0.0              0.5             0.5           0.5   
3            1.0              0.5             0.5           0.0   
4            0.0              1.0             0.0           0.0   

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0               0.0          0.0          0.0              0.0       0.0   
1               0.5          0.0          0.0              0.0       0.5   
2               0.0          0.0          0.0              0.0       0.0   
3               0.5          0.5          0.0              0.0       0.5   
4               0.0          0.0          0.0              0.0       0.0   

   PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0               1.0       0.000000        0.115423      0.003437    0.0  
1               0.0       0.333333        0.385075      0.217564    0.0  
2               1.0       0.333333        0.354229      0.012453    1.0  
3               0.0       0.666667        0.239303      0.211951    0.0  
4               1.0       0.000000        0.521891      0.017462    1.0

In [3]:
#prepare Data for training/testing
X=df.iloc[:,:-1]
y=df.iloc[:,-1]


In [4]:
X.shape

(7043, 19)

In [5]:
y.shape

(7043,)

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=21)

In [7]:
#KNN Model
knn=KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train,y_train)
yknn=knn.predict(X_test)
knnacc=accuracy_score(yknn,y_test)
knnmatrix=confusion_matrix(y_test,yknn)
knnreport=classification_report(y_test,yknn,output_dict=True)
print(knnacc)
print(knnmatrix)
print(knnreport)

0.7721788502484032
[[927 108]
 [213 161]]
{'0.0': {'precision': 0.8131578947368421, 'recall': 0.8956521739130435, 'f1-score': 0.8524137931034482, 'support': 1035.0}, '1.0': {'precision': 0.5985130111524164, 'recall': 0.4304812834224599, 'f1-score': 0.5007776049766719, 'support': 374.0}, 'accuracy': 0.7721788502484032, 'macro avg': {'precision': 0.7058354529446292, 'recall': 0.6630667286677517, 'f1-score': 0.6765956990400601, 'support': 1409.0}, 'weighted avg': {'precision': 0.7561833124369306, 'recall': 0.7721788502484032, 'f1-score': 0.7590767211663195, 'support': 1409.0}}


In [8]:
#SVC model
svc=SVC()
svc.fit(X_train,y_train)
ysvc=svc.predict(X_test)
svcacc=accuracy_score(ysvc,y_test)
svcmatrix=confusion_matrix(y_test,ysvc)
svcreport=classification_report(y_test,ysvc,output_dict=True)
print(svcacc)
print(svcmatrix)
print(svcreport)

0.794180269694819
[[939  96]
 [194 180]]
{'0.0': {'precision': 0.8287731685789939, 'recall': 0.9072463768115943, 'f1-score': 0.8662361623616236, 'support': 1035.0}, '1.0': {'precision': 0.6521739130434783, 'recall': 0.48128342245989303, 'f1-score': 0.5538461538461539, 'support': 374.0}, 'accuracy': 0.794180269694819, 'macro avg': {'precision': 0.7404735408112361, 'recall': 0.6942648996357437, 'f1-score': 0.7100411581038888, 'support': 1409.0}, 'weighted avg': {'precision': 0.7818972838591339, 'recall': 0.794180269694819, 'f1-score': 0.7833164581850546, 'support': 1409.0}}


In [9]:
#Logistic Regression Model
logreg=LogisticRegression(max_iter=1000)
logreg.fit(X_train,y_train)
ylogreg=logreg.predict(X_test)
logregacc=accuracy_score(ylogreg,y_test)
logregmatrix=confusion_matrix(y_test,ylogreg)
logregreport=classification_report(y_test,ylogreg,output_dict=True)
print(logregacc)
print(logregmatrix)
print(logregreport)

0.7906316536550745
[[921 114]
 [181 193]]
{'0.0': {'precision': 0.8357531760435571, 'recall': 0.8898550724637682, 'f1-score': 0.8619560131024802, 'support': 1035.0}, '1.0': {'precision': 0.6286644951140065, 'recall': 0.516042780748663, 'f1-score': 0.566813509544787, 'support': 374.0}, 'accuracy': 0.7906316536550745, 'macro avg': {'precision': 0.7322088355787818, 'recall': 0.7029489266062157, 'f1-score': 0.7143847613236336, 'support': 1409.0}, 'weighted avg': {'precision': 0.7807842855768062, 'recall': 0.7906316536550745, 'f1-score': 0.7836144259267688, 'support': 1409.0}}


In [10]:
#Tree Model
tree=DecisionTreeClassifier()
tree.fit(X_train,y_train)
ytree=tree.predict(X_test)
treeacc=accuracy_score(ytree,y_test)
treematrix=confusion_matrix(y_test,ytree)
treereport=classification_report(y_test,ytree,output_dict=True)
print(treeacc)
print(treematrix)
print(treereport)

0.7217885024840313
[[833 202]
 [190 184]]
{'0.0': {'precision': 0.8142717497556208, 'recall': 0.8048309178743961, 'f1-score': 0.8095238095238095, 'support': 1035.0}, '1.0': {'precision': 0.47668393782383417, 'recall': 0.4919786096256685, 'f1-score': 0.4842105263157895, 'support': 374.0}, 'accuracy': 0.7217885024840313, 'macro avg': {'precision': 0.6454778437897275, 'recall': 0.6484047637500323, 'f1-score': 0.6468671679197995, 'support': 1409.0}, 'weighted avg': {'precision': 0.7246636293422154, 'recall': 0.7217885024840313, 'f1-score': 0.7231737968057119, 'support': 1409.0}}


In [11]:
#Forest Model
forest=RandomForestClassifier()
forest.fit(X_train,y_train)
yforest=forest.predict(X_test)
forestacc=accuracy_score(yforest,y_test)
forestmatrix=confusion_matrix(y_test,yforest)
forestreport=classification_report(y_test,yforest,output_dict=True)
print(forestacc)
print(forestmatrix)
print(forestreport)

0.7821149751596878
[[925 110]
 [197 177]]
{'0.0': {'precision': 0.8244206773618539, 'recall': 0.893719806763285, 'f1-score': 0.8576726935558646, 'support': 1035.0}, '1.0': {'precision': 0.6167247386759582, 'recall': 0.4732620320855615, 'f1-score': 0.5355521936459909, 'support': 374.0}, 'accuracy': 0.7821149751596878, 'macro avg': {'precision': 0.720572708018906, 'recall': 0.6834909194244232, 'f1-score': 0.6966124436009278, 'support': 1409.0}, 'weighted avg': {'precision': 0.7692905985339441, 'recall': 0.7821149751596878, 'f1-score': 0.7721701619971046, 'support': 1409.0}}


In [33]:
metrics={
    "model":["normalknn","normalsvc","normalLogReg","normalTree","normalForest"],
    "precision":[knnreport["weighted avg"]["precision"],svcreport["weighted avg"]["precision"],logregreport["weighted avg"]["precision"],treereport["weighted avg"]["precision"],forestreport["weighted avg"]["precision"]],
    "recall":[knnreport["weighted avg"]["recall"],svcreport["weighted avg"]["recall"],logregreport["weighted avg"]["recall"],treereport["weighted avg"]["recall"],forestreport["weighted avg"]["recall"]],
    "f1":[knnreport["weighted avg"]['f1-score'],svcreport["weighted avg"]["f1-score"],logregreport["weighted avg"]["f1-score"],treereport["weighted avg"]["f1-score"],forestreport["weighted avg"]["f1-score"]]
}
metrics=pd.DataFrame(metrics)
metrics.head()

model  precision    recall        f1
0     normalknn   0.756183  0.772179  0.759077
1     normalsvc   0.781897  0.794180  0.783316
2  normalLogReg   0.780784  0.790632  0.783614
3    normalTree   0.724664  0.721789  0.723174
4  normalForest   0.769291  0.782115  0.772170

In [35]:
errors=pd.read_csv("Metrics.csv",index_col=0)
metrics=pd.concat([errors,metrics],ignore_index=True)
metrics

model  precision    recall        f1
0       baseknn   0.780759  0.792051  0.765596
1       basesvc   0.539584  0.734564  0.622155
2    baseLogReg   0.786733  0.794890  0.789405
3      baseTree   0.725576  0.723918  0.724729
4    baseForest   0.772494  0.786373  0.774088
5     normalknn   0.756183  0.772179  0.759077
6     normalsvc   0.781897  0.794180  0.783316
7  normalLogReg   0.780784  0.790632  0.783614
8    normalTree   0.724664  0.721789  0.723174
9  normalForest   0.769291  0.782115  0.772170

In [36]:
metrics.to_csv("metrics.csv")