In [29]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [30]:
#Training Models on Basic Data
df=pd.read_csv("Datasets/normaldata.csv")
df.drop(df.columns[0],axis=1,inplace=True)
df.head()

gender  SeniorCitizen  Partner  Dependents    tenure  PhoneService  \
0     1.0            0.0      1.0         0.0  0.013889           0.0   
1     0.0            0.0      0.0         0.0  0.472222           1.0   
2     0.0            0.0      0.0         0.0  0.027778           1.0   
3     0.0            0.0      0.0         0.0  0.625000           0.0   
4     1.0            0.0      0.0         0.0  0.027778           1.0   

   MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0            1.0              0.5             0.0           0.5   
1            0.0              0.5             0.5           0.0   
2            0.0              0.5             0.5           0.5   
3            1.0              0.5             0.5           0.0   
4            0.0              1.0             0.0           0.0   

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0               0.0          0.0          0.0              0.0       0.0   
1               0.5          0.0          0.0              0.0       0.5   
2               0.0          0.0          0.0              0.0       0.0   
3               0.5          0.5          0.0              0.0       0.5   
4               0.0          0.0          0.0              0.0       0.0   

   PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0               1.0       0.000000        0.115423      0.003437    0.0  
1               0.0       0.333333        0.385075      0.217564    0.0  
2               1.0       0.333333        0.354229      0.012453    1.0  
3               0.0       0.666667        0.239303      0.211951    0.0  
4               1.0       0.000000        0.521891      0.017462    1.0

In [31]:
#prepare Data for training/testing
X=df.iloc[:,:-1]
y=df.iloc[:,-1]


In [32]:
X.shape

(7043, 19)

In [33]:
y.shape

(7043,)

In [34]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=21)

In [35]:
#KNN Model
knn=KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train,y_train)
yknn=knn.predict(X_test)
knnacc=accuracy_score(yknn,y_test)
knnmatrix=confusion_matrix(y_test,yknn)
knnreport=classification_report(y_test,yknn,output_dict=True)
print(knnacc)
print(knnmatrix)
print(knnreport)

0.7721788502484032
[[927 108]
 [213 161]]
{'0.0': {'precision': 0.8131578947368421, 'recall': 0.8956521739130435, 'f1-score': 0.8524137931034482, 'support': 1035.0}, '1.0': {'precision': 0.5985130111524164, 'recall': 0.4304812834224599, 'f1-score': 0.5007776049766719, 'support': 374.0}, 'accuracy': 0.7721788502484032, 'macro avg': {'precision': 0.7058354529446292, 'recall': 0.6630667286677517, 'f1-score': 0.6765956990400601, 'support': 1409.0}, 'weighted avg': {'precision': 0.7561833124369306, 'recall': 0.7721788502484032, 'f1-score': 0.7590767211663195, 'support': 1409.0}}


In [36]:
#SVC model
svc=SVC()
svc.fit(X_train,y_train)
ysvc=svc.predict(X_test)
svcacc=accuracy_score(ysvc,y_test)
svcmatrix=confusion_matrix(y_test,ysvc)
svcreport=classification_report(y_test,ysvc,output_dict=True)
print(svcacc)
print(svcmatrix)
print(svcreport)

0.794180269694819
[[939  96]
 [194 180]]
{'0.0': {'precision': 0.8287731685789939, 'recall': 0.9072463768115943, 'f1-score': 0.8662361623616236, 'support': 1035.0}, '1.0': {'precision': 0.6521739130434783, 'recall': 0.48128342245989303, 'f1-score': 0.5538461538461539, 'support': 374.0}, 'accuracy': 0.794180269694819, 'macro avg': {'precision': 0.7404735408112361, 'recall': 0.6942648996357437, 'f1-score': 0.7100411581038888, 'support': 1409.0}, 'weighted avg': {'precision': 0.7818972838591339, 'recall': 0.794180269694819, 'f1-score': 0.7833164581850546, 'support': 1409.0}}


In [37]:
#Logistic Regression Model
logreg=LogisticRegression(max_iter=1000)
logreg.fit(X_train,y_train)
ylogreg=logreg.predict(X_test)
logregacc=accuracy_score(ylogreg,y_test)
logregmatrix=confusion_matrix(y_test,ylogreg)
logregreport=classification_report(y_test,ylogreg,output_dict=True)
print(logregacc)
print(logregmatrix)
print(logregreport)

0.7906316536550745
[[921 114]
 [181 193]]
{'0.0': {'precision': 0.8357531760435571, 'recall': 0.8898550724637682, 'f1-score': 0.8619560131024802, 'support': 1035.0}, '1.0': {'precision': 0.6286644951140065, 'recall': 0.516042780748663, 'f1-score': 0.566813509544787, 'support': 374.0}, 'accuracy': 0.7906316536550745, 'macro avg': {'precision': 0.7322088355787818, 'recall': 0.7029489266062157, 'f1-score': 0.7143847613236336, 'support': 1409.0}, 'weighted avg': {'precision': 0.7807842855768062, 'recall': 0.7906316536550745, 'f1-score': 0.7836144259267688, 'support': 1409.0}}


In [38]:
#Tree Model
tree=DecisionTreeClassifier()
tree.fit(X_train,y_train)
ytree=tree.predict(X_test)
treeacc=accuracy_score(ytree,y_test)
treematrix=confusion_matrix(y_test,ytree)
treereport=classification_report(y_test,ytree,output_dict=True)
print(treeacc)
print(treematrix)
print(treereport)

0.7210787792760823
[[835 200]
 [193 181]]
{'0.0': {'precision': 0.8122568093385214, 'recall': 0.8067632850241546, 'f1-score': 0.8095007270964615, 'support': 1035.0}, '1.0': {'precision': 0.47506561679790027, 'recall': 0.4839572192513369, 'f1-score': 0.4794701986754967, 'support': 374.0}, 'accuracy': 0.7210787792760823, 'macro avg': {'precision': 0.6436612130682109, 'recall': 0.6453602521377457, 'f1-score': 0.6444854628859791, 'support': 1409.0}, 'weighted avg': {'precision': 0.7227539661801167, 'recall': 0.7210787792760823, 'f1-score': 0.7218985854148143, 'support': 1409.0}}


In [39]:
#Forest Model
forest=RandomForestClassifier()
forest.fit(X_train,y_train)
yforest=forest.predict(X_test)
forestacc=accuracy_score(yforest,y_test)
forestmatrix=confusion_matrix(y_test,yforest)
forestreport=classification_report(y_test,yforest,output_dict=True)
print(forestacc)
print(forestmatrix)
print(forestreport)

0.7970191625266146
[[942  93]
 [193 181]]
{'0.0': {'precision': 0.8299559471365638, 'recall': 0.9101449275362319, 'f1-score': 0.8682027649769585, 'support': 1035.0}, '1.0': {'precision': 0.6605839416058394, 'recall': 0.4839572192513369, 'f1-score': 0.558641975308642, 'support': 374.0}, 'accuracy': 0.7970191625266146, 'macro avg': {'precision': 0.7452699443712016, 'recall': 0.6970510733937844, 'f1-score': 0.7134223701428002, 'support': 1409.0}, 'weighted avg': {'precision': 0.7849984382164141, 'recall': 0.7970191625266146, 'f1-score': 0.786034038691685, 'support': 1409.0}}


In [40]:
metrics={
    "model":["normalknn","normalsvc","normalLogReg","normalTree","normalForest"],
    "precision":[knnreport["weighted avg"]["precision"],svcreport["weighted avg"]["precision"],logregreport["weighted avg"]["precision"],treereport["weighted avg"]["precision"],forestreport["weighted avg"]["precision"]],
    "recall":[knnreport["weighted avg"]["recall"],svcreport["weighted avg"]["recall"],logregreport["weighted avg"]["recall"],treereport["weighted avg"]["recall"],forestreport["weighted avg"]["recall"]],
    "f1":[knnreport["weighted avg"]['f1-score'],svcreport["weighted avg"]["f1-score"],logregreport["weighted avg"]["f1-score"],treereport["weighted avg"]["f1-score"],forestreport["weighted avg"]["f1-score"]]
}
metrics=pd.DataFrame(metrics)
metrics.head()

model  precision    recall        f1
0     normalknn   0.756183  0.772179  0.759077
1     normalsvc   0.781897  0.794180  0.783316
2  normalLogReg   0.780784  0.790632  0.783614
3    normalTree   0.722754  0.721079  0.721899
4  normalForest   0.784998  0.797019  0.786034

In [41]:
errors=pd.read_csv("Metrics.csv",index_col=0)
metrics=pd.concat([errors,metrics],ignore_index=True)
metrics

model  precision    recall        f1
0        baseknn   0.780759  0.792051  0.765596
1        basesvc   0.539584  0.734564  0.622155
2     baseLogReg   0.786733  0.794890  0.789405
3       baseTree   0.725576  0.723918  0.724729
4     baseForest   0.772494  0.786373  0.774088
5      normalknn   0.756183  0.772179  0.759077
6      normalsvc   0.781897  0.794180  0.783316
7   normalLogReg   0.780784  0.790632  0.783614
8     normalTree   0.724664  0.721789  0.723174
9   normalForest   0.769291  0.782115  0.772170
10        stdknn   0.761861  0.773598  0.765480
11        stdsvc   0.785510  0.797019  0.787104
12     stdLogReg   0.779081  0.788502  0.782020
13       stdTree   0.721343  0.719659  0.720483
14     stdForest   0.766697  0.780696  0.769265
15        pcaknn   0.760183  0.776437  0.762013
16        pcasvc   0.763511  0.779276  0.765035
17     pcaLogReg   0.748492  0.765791  0.751837
18       pcaTree   0.717102  0.721789  0.719298
19     pcaForest   0.748028  0.765082  0.751571
20       pca2knn   0.760165  0.775727  0.762675
21       pca2svc   0.784779  0.797019  0.785485
22    pca2LogReg   0.782549  0.792761  0.785207
23      pca2Tree   0.734541  0.739532  0.736831
24    pca2Forest   0.760021  0.774308  0.763284
25     normalknn   0.756183  0.772179  0.759077
26     normalsvc   0.781897  0.794180  0.783316
27  normalLogReg   0.780784  0.790632  0.783614
28    normalTree   0.722754  0.721079  0.721899
29  normalForest   0.784998  0.797019  0.786034

In [42]:
metrics.to_csv("metrics.csv")