In [48]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [49]:
#Training Models on Basic Data
df=pd.read_csv("Datasets/normaldata.csv")
df.drop(df.columns[0],axis=1,inplace=True)
df.head()

gender  SeniorCitizen  Partner  Dependents    tenure  PhoneService  \
0     1.0            0.0      1.0         0.0  0.013889           0.0   
1     0.0            0.0      0.0         0.0  0.472222           1.0   
2     0.0            0.0      0.0         0.0  0.027778           1.0   
3     0.0            0.0      0.0         0.0  0.625000           0.0   
4     1.0            0.0      0.0         0.0  0.027778           1.0   

   MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0            1.0              0.5             0.0           0.5   
1            0.0              0.5             0.5           0.0   
2            0.0              0.5             0.5           0.5   
3            1.0              0.5             0.5           0.0   
4            0.0              1.0             0.0           0.0   

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0               0.0          0.0          0.0              0.0       0.0   
1               0.5          0.0          0.0              0.0       0.5   
2               0.0          0.0          0.0              0.0       0.0   
3               0.5          0.5          0.0              0.0       0.5   
4               0.0          0.0          0.0              0.0       0.0   

   PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0               1.0       0.000000        0.115423      0.003437    0.0  
1               0.0       0.333333        0.385075      0.217564    0.0  
2               1.0       0.333333        0.354229      0.012453    1.0  
3               0.0       0.666667        0.239303      0.211951    0.0  
4               1.0       0.000000        0.521891      0.017462    1.0

In [50]:
#prepare Data for training/testing
X=df.iloc[:,:-1]
y=df.iloc[:,-1]


In [51]:
X.shape

(7043, 19)

In [52]:
y.shape

(7043,)

In [53]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=21)

In [54]:
#KNN Model
knn=KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train,y_train)
yknn=knn.predict(X_test)
knnacc=accuracy_score(yknn,y_test)
knnmatrix=confusion_matrix(y_test,yknn)
knnreport=classification_report(y_test,yknn,output_dict=True)
print(knnacc)
print(knnmatrix)
print(knnreport)

0.7721788502484032
[[927 108]
 [213 161]]
{'0.0': {'precision': 0.8131578947368421, 'recall': 0.8956521739130435, 'f1-score': 0.8524137931034482, 'support': 1035.0}, '1.0': {'precision': 0.5985130111524164, 'recall': 0.4304812834224599, 'f1-score': 0.5007776049766719, 'support': 374.0}, 'accuracy': 0.7721788502484032, 'macro avg': {'precision': 0.7058354529446292, 'recall': 0.6630667286677517, 'f1-score': 0.6765956990400601, 'support': 1409.0}, 'weighted avg': {'precision': 0.7561833124369306, 'recall': 0.7721788502484032, 'f1-score': 0.7590767211663195, 'support': 1409.0}}


In [55]:
#SVC model
svc=SVC()
svc.fit(X_train,y_train)
ysvc=svc.predict(X_test)
svcacc=accuracy_score(ysvc,y_test)
svcmatrix=confusion_matrix(y_test,ysvc)
svcreport=classification_report(y_test,ysvc,output_dict=True)
print(svcacc)
print(svcmatrix)
print(svcreport)

0.794180269694819
[[939  96]
 [194 180]]
{'0.0': {'precision': 0.8287731685789939, 'recall': 0.9072463768115943, 'f1-score': 0.8662361623616236, 'support': 1035.0}, '1.0': {'precision': 0.6521739130434783, 'recall': 0.48128342245989303, 'f1-score': 0.5538461538461539, 'support': 374.0}, 'accuracy': 0.794180269694819, 'macro avg': {'precision': 0.7404735408112361, 'recall': 0.6942648996357437, 'f1-score': 0.7100411581038888, 'support': 1409.0}, 'weighted avg': {'precision': 0.7818972838591339, 'recall': 0.794180269694819, 'f1-score': 0.7833164581850546, 'support': 1409.0}}


In [56]:
#Logistic Regression Model
logreg=LogisticRegression(max_iter=1000)
logreg.fit(X_train,y_train)
ylogreg=logreg.predict(X_test)
logregacc=accuracy_score(ylogreg,y_test)
logregmatrix=confusion_matrix(y_test,ylogreg)
logregreport=classification_report(y_test,ylogreg,output_dict=True)
print(logregacc)
print(logregmatrix)
print(logregreport)

0.7906316536550745
[[921 114]
 [181 193]]
{'0.0': {'precision': 0.8357531760435571, 'recall': 0.8898550724637682, 'f1-score': 0.8619560131024802, 'support': 1035.0}, '1.0': {'precision': 0.6286644951140065, 'recall': 0.516042780748663, 'f1-score': 0.566813509544787, 'support': 374.0}, 'accuracy': 0.7906316536550745, 'macro avg': {'precision': 0.7322088355787818, 'recall': 0.7029489266062157, 'f1-score': 0.7143847613236336, 'support': 1409.0}, 'weighted avg': {'precision': 0.7807842855768062, 'recall': 0.7906316536550745, 'f1-score': 0.7836144259267688, 'support': 1409.0}}


In [57]:
#Tree Model
tree=DecisionTreeClassifier()
tree.fit(X_train,y_train)
ytree=tree.predict(X_test)
treeacc=accuracy_score(ytree,y_test)
treematrix=confusion_matrix(y_test,ytree)
treereport=classification_report(y_test,ytree,output_dict=True)
print(treeacc)
print(treematrix)
print(treereport)

0.7203690560681334
[[834 201]
 [193 181]]
{'0.0': {'precision': 0.8120740019474196, 'recall': 0.8057971014492754, 'f1-score': 0.8089233753637245, 'support': 1035.0}, '1.0': {'precision': 0.4738219895287958, 'recall': 0.4839572192513369, 'f1-score': 0.47883597883597884, 'support': 374.0}, 'accuracy': 0.7203690560681334, 'macro avg': {'precision': 0.6429479957381077, 'recall': 0.6448771603503062, 'f1-score': 0.6438796770998516, 'support': 1409.0}, 'weighted avg': {'precision': 0.7222895784949247, 'recall': 0.7203690560681334, 'f1-score': 0.7213061388120021, 'support': 1409.0}}


In [58]:
#Forest Model
forest=RandomForestClassifier()
forest.fit(X_train,y_train)
yforest=forest.predict(X_test)
forestacc=accuracy_score(yforest,y_test)
forestmatrix=confusion_matrix(y_test,yforest)
forestreport=classification_report(y_test,yforest,output_dict=True)
print(forestacc)
print(forestmatrix)
print(forestreport)

0.7920511000709723
[[936  99]
 [194 180]]
{'0.0': {'precision': 0.8283185840707965, 'recall': 0.9043478260869565, 'f1-score': 0.8646651270207852, 'support': 1035.0}, '1.0': {'precision': 0.6451612903225806, 'recall': 0.48128342245989303, 'f1-score': 0.5513016845329249, 'support': 374.0}, 'accuracy': 0.7920511000709723, 'macro avg': {'precision': 0.7367399371966885, 'recall': 0.6928156242734248, 'f1-score': 0.707983405776855, 'support': 1409.0}, 'weighted avg': {'precision': 0.7797019567735411, 'recall': 0.7920511000709723, 'f1-score': 0.7814870379572935, 'support': 1409.0}}
