In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [2]:
#Training Models on Basic Data
df=pd.read_csv("Datasets/PCA2data.csv")
df.drop(df.columns[0],axis=1,inplace=True)
df.head()

PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
0 -1.901289 -1.677362 -3.782398 -0.177749 -1.385649  1.112263 -0.703578   
1 -0.663606 -0.818212  0.208648  0.479259  1.782965 -1.060120  0.612599   
2 -1.197334 -2.291034  0.481391  0.352736  0.687814 -0.942323 -0.495574   
3 -0.448424 -0.080102 -4.020620 -0.891912  1.537617 -0.991623  0.246803   
4 -2.759017 -2.170904  0.897915  0.360015  0.302903  1.019008 -0.724327   

        PC8       PC9      PC10  Churn  
0  0.026582  0.542130  1.413739      0  
1 -0.883878  1.026004 -0.113518      0  
2  0.778095  0.959643  0.117506      1  
3 -0.542467  0.089424 -0.110527      0  
4 -0.127049  0.694728 -0.047476      1

In [3]:
#prepare Data for training/testing
X=df.iloc[:,:-1]
y=df.iloc[:,-1]


In [4]:
X.shape

(7043, 10)

In [5]:
y.shape

(7043,)

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=21)

In [7]:
#KNN Model
knn=KNeighborsClassifier(n_neighbors=20)
knn.fit(X_train,y_train)
yknn=knn.predict(X_test)
knnacc=accuracy_score(yknn,y_test)
knnmatrix=confusion_matrix(y_test,yknn)
knnreport=classification_report(y_test,yknn,output_dict=True)
print(knnacc)
print(knnmatrix)
print(knnreport)

0.7757274662881476
[[930 105]
 [211 163]]
{'0': {'precision': 0.8150744960560912, 'recall': 0.8985507246376812, 'f1-score': 0.8547794117647058, 'support': 1035.0}, '1': {'precision': 0.6082089552238806, 'recall': 0.4358288770053476, 'f1-score': 0.5077881619937694, 'support': 374.0}, 'accuracy': 0.7757274662881476, 'macro avg': {'precision': 0.7116417256399858, 'recall': 0.6671898008215144, 'f1-score': 0.6812837868792376, 'support': 1409.0}, 'weighted avg': {'precision': 0.7601648351112744, 'recall': 0.7757274662881476, 'f1-score': 0.7626752759135133, 'support': 1409.0}}


In [8]:
#SVC model
svc=SVC()
svc.fit(X_train,y_train)
ysvc=svc.predict(X_test)
svcacc=accuracy_score(ysvc,y_test)
svcmatrix=confusion_matrix(y_test,ysvc)
svcreport=classification_report(y_test,ysvc,output_dict=True)
print(svcacc)
print(svcmatrix)
print(svcreport)

0.7970191625266146
[[944  91]
 [195 179]]
{'0': {'precision': 0.8287971905179983, 'recall': 0.9120772946859903, 'f1-score': 0.8684452621895125, 'support': 1035.0}, '1': {'precision': 0.662962962962963, 'recall': 0.4786096256684492, 'f1-score': 0.5559006211180124, 'support': 374.0}, 'accuracy': 0.7970191625266146, 'macro avg': {'precision': 0.7458800767404806, 'recall': 0.6953434601772197, 'f1-score': 0.7121729416537624, 'support': 1409.0}, 'weighted avg': {'precision': 0.7847787369299335, 'recall': 0.7970191625266146, 'f1-score': 0.7854845128916125, 'support': 1409.0}}


In [9]:
#Logistic Regression Model
logreg=LogisticRegression(max_iter=1000)
logreg.fit(X_train,y_train)
ylogreg=logreg.predict(X_test)
logregacc=accuracy_score(ylogreg,y_test)
logregmatrix=confusion_matrix(y_test,ylogreg)
logregreport=classification_report(y_test,ylogreg,output_dict=True)
print(logregacc)
print(logregmatrix)
print(logregreport)

0.7927608232789212
[[925 110]
 [182 192]]
{'0': {'precision': 0.8355916892502259, 'recall': 0.893719806763285, 'f1-score': 0.8636788048552755, 'support': 1035.0}, '1': {'precision': 0.6357615894039735, 'recall': 0.5133689839572193, 'f1-score': 0.5680473372781065, 'support': 374.0}, 'accuracy': 0.7927608232789212, 'macro avg': {'precision': 0.7356766393270997, 'recall': 0.7035443953602522, 'f1-score': 0.715863071066691, 'support': 1409.0}, 'weighted avg': {'precision': 0.7825494909943718, 'recall': 0.7927608232789212, 'f1-score': 0.785207428791499, 'support': 1409.0}}


In [10]:
#Tree Model
tree=DecisionTreeClassifier()
tree.fit(X_train,y_train)
ytree=tree.predict(X_test)
treeacc=accuracy_score(ytree,y_test)
treematrix=confusion_matrix(y_test,ytree)
treereport=classification_report(y_test,ytree,output_dict=True)
print(treeacc)
print(treematrix)
print(treereport)

0.7395315826827538
[[863 172]
 [195 179]]
{'0': {'precision': 0.8156899810964083, 'recall': 0.8338164251207729, 'f1-score': 0.824653607262303, 'support': 1035.0}, '1': {'precision': 0.50997150997151, 'recall': 0.4786096256684492, 'f1-score': 0.49379310344827587, 'support': 374.0}, 'accuracy': 0.7395315826827538, 'macro avg': {'precision': 0.6628307455339592, 'recall': 0.656213025394611, 'f1-score': 0.6592233553552894, 'support': 1409.0}, 'weighted avg': {'precision': 0.7345411463194658, 'recall': 0.7395315826827538, 'f1-score': 0.7368311598340233, 'support': 1409.0}}


In [11]:
#Forest Model
forest=RandomForestClassifier()
forest.fit(X_train,y_train)
yforest=forest.predict(X_test)
forestacc=accuracy_score(yforest,y_test)
forestmatrix=confusion_matrix(y_test,yforest)
forestreport=classification_report(y_test,yforest,output_dict=True)
print(forestacc)
print(forestmatrix)
print(forestreport)

0.7743080198722498
[[922 113]
 [205 169]]
{'0': {'precision': 0.8181011535048802, 'recall': 0.8908212560386474, 'f1-score': 0.8529139685476411, 'support': 1035.0}, '1': {'precision': 0.599290780141844, 'recall': 0.45187165775401067, 'f1-score': 0.5152439024390244, 'support': 374.0}, 'accuracy': 0.7743080198722498, 'macro avg': {'precision': 0.7086959668233621, 'recall': 0.671346456896329, 'f1-score': 0.6840789354933328, 'support': 1409.0}, 'weighted avg': {'precision': 0.7600208982616045, 'recall': 0.7743080198722498, 'f1-score': 0.7632840148750912, 'support': 1409.0}}


In [12]:
metrics={
    "model":["pca2knn","pca2svc","pca2LogReg","pca2Tree","pca2Forest"],
    "precision":[knnreport["weighted avg"]["precision"],svcreport["weighted avg"]["precision"],logregreport["weighted avg"]["precision"],treereport["weighted avg"]["precision"],forestreport["weighted avg"]["precision"]],
    "recall":[knnreport["weighted avg"]["recall"],svcreport["weighted avg"]["recall"],logregreport["weighted avg"]["recall"],treereport["weighted avg"]["recall"],forestreport["weighted avg"]["recall"]],
    "f1":[knnreport["weighted avg"]['f1-score'],svcreport["weighted avg"]["f1-score"],logregreport["weighted avg"]["f1-score"],treereport["weighted avg"]["f1-score"],forestreport["weighted avg"]["f1-score"]]
}
metrics=pd.DataFrame(metrics)
metrics.head()

model  precision    recall        f1
0     pca2knn   0.760165  0.775727  0.762675
1     pca2svc   0.784779  0.797019  0.785485
2  pca2LogReg   0.782549  0.792761  0.785207
3    pca2Tree   0.734541  0.739532  0.736831
4  pca2Forest   0.760021  0.774308  0.763284

In [13]:
errors=pd.read_csv("Metrics.csv",index_col=0)
metrics=pd.concat([errors,metrics],ignore_index=True)
metrics

model  precision    recall        f1
0        baseknn   0.780759  0.792051  0.765596
1        basesvc   0.539584  0.734564  0.622155
2     baseLogReg   0.786733  0.794890  0.789405
3       baseTree   0.725576  0.723918  0.724729
4     baseForest   0.772494  0.786373  0.774088
5      normalknn   0.756183  0.772179  0.759077
6      normalsvc   0.781897  0.794180  0.783316
7   normalLogReg   0.780784  0.790632  0.783614
8     normalTree   0.724664  0.721789  0.723174
9   normalForest   0.769291  0.782115  0.772170
10        stdknn   0.761861  0.773598  0.765480
11        stdsvc   0.785510  0.797019  0.787104
12     stdLogReg   0.779081  0.788502  0.782020
13       stdTree   0.721343  0.719659  0.720483
14     stdForest   0.766697  0.780696  0.769265
15        pcaknn   0.760183  0.776437  0.762013
16        pcasvc   0.763511  0.779276  0.765035
17     pcaLogReg   0.748492  0.765791  0.751837
18       pcaTree   0.717102  0.721789  0.719298
19     pcaForest   0.748028  0.765082  0.751571
20       pca2knn   0.760165  0.775727  0.762675
21       pca2svc   0.784779  0.797019  0.785485
22    pca2LogReg   0.782549  0.792761  0.785207
23      pca2Tree   0.734541  0.739532  0.736831
24    pca2Forest   0.760021  0.774308  0.763284

In [14]:
metrics.to_csv("metrics.csv")