In [24]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [25]:
#Training Models on Basic Data
df=pd.read_csv("Datasets/PCA2data.csv")
df.drop(df.columns[0],axis=1,inplace=True)
df.head()

PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
0 -1.885565 -1.627535 -3.799837 -0.182696 -1.362440  1.103571 -0.684011   
1 -0.646615 -0.784016  0.184520  0.505069  1.821955 -1.052056  0.609788   
2 -1.249324 -2.326943  0.484803  0.351301  0.663322 -0.937333 -0.506802   
3 -0.426911 -0.039064 -4.032692 -0.883347  1.549508 -0.983663  0.238264   
4 -2.808463 -2.197336  0.899597  0.358118  0.275047  1.021632 -0.730290   

        PC8       PC9      PC10  Churn  
0  0.024141  0.599607  1.411833      0  
1 -0.883644  1.029785 -0.109038      0  
2  0.778873  0.905291  0.125722      1  
3 -0.541664  0.084028 -0.109990      0  
4 -0.126808  0.651876 -0.040851      1

In [26]:
#prepare Data for training/testing
X=df.iloc[:,:-1]
y=df.iloc[:,-1]


In [27]:
X.shape

(7043, 10)

In [28]:
y.shape

(7043,)

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=21)

In [30]:
#KNN Model
knn=KNeighborsClassifier(n_neighbors=20)
knn.fit(X_train,y_train)
yknn=knn.predict(X_test)
knnacc=accuracy_score(yknn,y_test)
knnmatrix=confusion_matrix(y_test,yknn)
knnreport=classification_report(y_test,yknn,output_dict=True)
print(knnacc)
print(knnmatrix)
print(knnreport)

0.7913413768630234
[[939  96]
 [198 176]]
{'0': {'precision': 0.8258575197889182, 'recall': 0.9072463768115943, 'f1-score': 0.8646408839779005, 'support': 1035.0}, '1': {'precision': 0.6470588235294118, 'recall': 0.47058823529411764, 'f1-score': 0.544891640866873, 'support': 374.0}, 'accuracy': 0.7913413768630234, 'macro avg': {'precision': 0.7364581716591649, 'recall': 0.688917306052856, 'f1-score': 0.7047662624223867, 'support': 1409.0}, 'weighted avg': {'precision': 0.7783978232658129, 'recall': 0.7913413768630234, 'f1-score': 0.7797677704764638, 'support': 1409.0}}


In [31]:
#SVC model
svc=SVC()
svc.fit(X_train,y_train)
ysvc=svc.predict(X_test)
svcacc=accuracy_score(ysvc,y_test)
svcmatrix=confusion_matrix(y_test,ysvc)
svcreport=classification_report(y_test,ysvc,output_dict=True)
print(svcacc)
print(svcmatrix)
print(svcreport)

0.8190205819730305
[[954  81]
 [174 200]]
{'0': {'precision': 0.8457446808510638, 'recall': 0.9217391304347826, 'f1-score': 0.8821081830790569, 'support': 1035.0}, '1': {'precision': 0.7117437722419929, 'recall': 0.5347593582887701, 'f1-score': 0.6106870229007634, 'support': 374.0}, 'accuracy': 0.8190205819730305, 'macro avg': {'precision': 0.7787442265465283, 'recall': 0.7282492443617763, 'f1-score': 0.7463976029899102, 'support': 1409.0}, 'weighted avg': {'precision': 0.8101759513835034, 'recall': 0.8190205819730305, 'f1-score': 0.8100631057854574, 'support': 1409.0}}


In [32]:
#Logistic Regression Model
logreg=LogisticRegression(max_iter=1000)
logreg.fit(X_train,y_train)
ylogreg=logreg.predict(X_test)
logregacc=accuracy_score(ylogreg,y_test)
logregmatrix=confusion_matrix(y_test,ylogreg)
logregreport=classification_report(y_test,ylogreg,output_dict=True)
print(logregacc)
print(logregmatrix)
print(logregreport)

0.8119233498935415
[[937  98]
 [167 207]]
{'0': {'precision': 0.8487318840579711, 'recall': 0.9053140096618357, 'f1-score': 0.8761103319308088, 'support': 1035.0}, '1': {'precision': 0.6786885245901639, 'recall': 0.553475935828877, 'f1-score': 0.6097201767304861, 'support': 374.0}, 'accuracy': 0.8119233498935415, 'macro avg': {'precision': 0.7637102043240676, 'recall': 0.7293949727453564, 'f1-score': 0.7429152543306474, 'support': 1409.0}, 'weighted avg': {'precision': 0.8035961733120803, 'recall': 0.8119233498935415, 'f1-score': 0.8054006668882816, 'support': 1409.0}}


In [33]:
#Tree Model
tree=DecisionTreeClassifier()
tree.fit(X_train,y_train)
ytree=tree.predict(X_test)
treeacc=accuracy_score(ytree,y_test)
treematrix=confusion_matrix(y_test,ytree)
treereport=classification_report(y_test,ytree,output_dict=True)
print(treeacc)
print(treematrix)
print(treereport)

0.7955997161107168
[[907 128]
 [160 214]]
{'0': {'precision': 0.8500468603561387, 'recall': 0.8763285024154589, 'f1-score': 0.8629876308277831, 'support': 1035.0}, '1': {'precision': 0.6257309941520468, 'recall': 0.5721925133689839, 'f1-score': 0.5977653631284916, 'support': 374.0}, 'accuracy': 0.7955997161107168, 'macro avg': {'precision': 0.7378889272540927, 'recall': 0.7242605078922214, 'f1-score': 0.7303764969781373, 'support': 1409.0}, 'weighted avg': {'precision': 0.7905052464737182, 'recall': 0.7955997161107168, 'f1-score': 0.7925879657323005, 'support': 1409.0}}


In [34]:
#Forest Model
forest=RandomForestClassifier()
forest.fit(X_train,y_train)
yforest=forest.predict(X_test)
forestacc=accuracy_score(yforest,y_test)
forestmatrix=confusion_matrix(y_test,yforest)
forestreport=classification_report(y_test,yforest,output_dict=True)
print(forestacc)
print(forestmatrix)
print(forestreport)

0.8431511710432931
[[972  63]
 [158 216]]
{'0': {'precision': 0.8601769911504424, 'recall': 0.9391304347826087, 'f1-score': 0.8979214780600462, 'support': 1035.0}, '1': {'precision': 0.7741935483870968, 'recall': 0.5775401069518716, 'f1-score': 0.6615620214395099, 'support': 374.0}, 'accuracy': 0.8431511710432931, 'macro avg': {'precision': 0.8171852697687696, 'recall': 0.7583352708672402, 'f1-score': 0.7797417497497781, 'support': 1409.0}, 'weighted avg': {'precision': 0.8373538487845864, 'recall': 0.8431511710432931, 'f1-score': 0.8351830559336582, 'support': 1409.0}}


In [35]:
metrics={
    "model":["pca2knn","pca2svc","pca2LogReg","pca2Tree","pca2Forest"],
    "precision":[knnreport["weighted avg"]["precision"],svcreport["weighted avg"]["precision"],logregreport["weighted avg"]["precision"],treereport["weighted avg"]["precision"],forestreport["weighted avg"]["precision"]],
    "recall":[knnreport["weighted avg"]["recall"],svcreport["weighted avg"]["recall"],logregreport["weighted avg"]["recall"],treereport["weighted avg"]["recall"],forestreport["weighted avg"]["recall"]],
    "f1":[knnreport["weighted avg"]['f1-score'],svcreport["weighted avg"]["f1-score"],logregreport["weighted avg"]["f1-score"],treereport["weighted avg"]["f1-score"],forestreport["weighted avg"]["f1-score"]]
}
metrics=pd.DataFrame(metrics)
metrics.head()

model  precision    recall        f1
0     pca2knn   0.778398  0.791341  0.779768
1     pca2svc   0.810176  0.819021  0.810063
2  pca2LogReg   0.803596  0.811923  0.805401
3    pca2Tree   0.790505  0.795600  0.792588
4  pca2Forest   0.837354  0.843151  0.835183

In [ ]:
errors=pd.read_csv("Metrics.csv",index_col=0)
metrics=pd.concat([errors,metrics],ignore_index=True)
metrics

model  precision    recall        f1
0        baseknn   0.780759  0.792051  0.765596
1        basesvc   0.539584  0.734564  0.622155
2     baseLogReg   0.786733  0.794890  0.789405
3       baseTree   0.725576  0.723918  0.724729
4     baseForest   0.772494  0.786373  0.774088
5      normalknn   0.756183  0.772179  0.759077
6      normalsvc   0.781897  0.794180  0.783316
7   normalLogReg   0.780784  0.790632  0.783614
8     normalTree   0.724664  0.721789  0.723174
9   normalForest   0.769291  0.782115  0.772170
10        stdknn   0.761861  0.773598  0.765480
11        stdsvc   0.785510  0.797019  0.787104
12     stdLogReg   0.779081  0.788502  0.782020
13       stdTree   0.721343  0.719659  0.720483
14     stdForest   0.766697  0.780696  0.769265
15        pcaknn   0.760183  0.776437  0.762013
16        pcasvc   0.763511  0.779276  0.765035
17     pcaLogReg   0.748492  0.765791  0.751837
18       pcaTree   0.717102  0.721789  0.719298
19     pcaForest   0.748028  0.765082  0.751571
20       pca2knn   0.760165  0.775727  0.762675
21       pca2svc   0.784779  0.797019  0.785485
22    pca2LogReg   0.782549  0.792761  0.785207
23      pca2Tree   0.734541  0.739532  0.736831
24    pca2Forest   0.760021  0.774308  0.763284

In [ ]:
metrics.to_csv("metrics.csv")