In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [2]:
#Training Models on Basic Data
df=pd.read_csv("Datasets/PCAdata.csv")
df.drop(df.columns[0],axis=1,inplace=True)
df.head()

PC1       PC2       PC3  Churn
0 -1.901289 -1.677362 -3.782398      0
1 -0.663606 -0.818212  0.208648      0
2 -1.197334 -2.291034  0.481391      1
3 -0.448424 -0.080102 -4.020620      0
4 -2.759017 -2.170904  0.897915      1

In [3]:
#prepare Data for training/testing
X=df.iloc[:,:-1]
y=df.iloc[:,-1]


In [4]:
X.shape

(7043, 3)

In [5]:
y.shape

(7043,)

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=21)

In [7]:
#KNN Model
knn=KNeighborsClassifier(n_neighbors=20)
knn.fit(X_train,y_train)
yknn=knn.predict(X_test)
knnacc=accuracy_score(yknn,y_test)
knnmatrix=confusion_matrix(y_test,yknn)
knnreport=classification_report(y_test,yknn,output_dict=True)
print(knnacc)
print(knnmatrix)
print(knnreport)

0.7764371894960965
[[935 100]
 [215 159]]
{'0': {'precision': 0.8130434782608695, 'recall': 0.9033816425120773, 'f1-score': 0.8558352402745996, 'support': 1035.0}, '1': {'precision': 0.6138996138996139, 'recall': 0.42513368983957217, 'f1-score': 0.5023696682464455, 'support': 374.0}, 'accuracy': 0.7764371894960965, 'macro avg': {'precision': 0.7134715460802417, 'recall': 0.6642576661758247, 'f1-score': 0.6791024542605225, 'support': 1409.0}, 'weighted avg': {'precision': 0.7601834319364482, 'recall': 0.7764371894960965, 'f1-score': 0.7620125831145359, 'support': 1409.0}}


In [8]:
#SVC model
svc=SVC()
svc.fit(X_train,y_train)
ysvc=svc.predict(X_test)
svcacc=accuracy_score(ysvc,y_test)
svcmatrix=confusion_matrix(y_test,ysvc)
svcreport=classification_report(y_test,ysvc,output_dict=True)
print(svcacc)
print(svcmatrix)
print(svcreport)

0.7792760823278921
[[937  98]
 [213 161]]
{'0': {'precision': 0.8147826086956522, 'recall': 0.9053140096618357, 'f1-score': 0.8576659038901602, 'support': 1035.0}, '1': {'precision': 0.6216216216216216, 'recall': 0.4304812834224599, 'f1-score': 0.5086887835703001, 'support': 374.0}, 'accuracy': 0.7792760823278921, 'macro avg': {'precision': 0.7182021151586369, 'recall': 0.6678976465421478, 'f1-score': 0.6831773437302302, 'support': 1409.0}, 'weighted avg': {'precision': 0.7635106362572652, 'recall': 0.7792760823278921, 'f1-score': 0.7650346455511767, 'support': 1409.0}}


In [9]:
#Logistic Regression Model
logreg=LogisticRegression(max_iter=1000)
logreg.fit(X_train,y_train)
ylogreg=logreg.predict(X_test)
logregacc=accuracy_score(ylogreg,y_test)
logregmatrix=confusion_matrix(y_test,ylogreg)
logregreport=classification_report(y_test,ylogreg,output_dict=True)
print(logregacc)
print(logregmatrix)
print(logregreport)

0.765791341376863
[[924 111]
 [219 155]]
{'0': {'precision': 0.8083989501312336, 'recall': 0.8927536231884058, 'f1-score': 0.8484848484848485, 'support': 1035.0}, '1': {'precision': 0.5827067669172933, 'recall': 0.4144385026737968, 'f1-score': 0.484375, 'support': 374.0}, 'accuracy': 0.765791341376863, 'macro avg': {'precision': 0.6955528585242634, 'recall': 0.6535960629311013, 'f1-score': 0.6664299242424243, 'support': 1409.0}, 'weighted avg': {'precision': 0.7484920115066676, 'recall': 0.765791341376863, 'f1-score': 0.7518368120523905, 'support': 1409.0}}


In [10]:
#Tree Model
tree=DecisionTreeClassifier()
tree.fit(X_train,y_train)
ytree=tree.predict(X_test)
treeacc=accuracy_score(ytree,y_test)
treematrix=confusion_matrix(y_test,ytree)
treereport=classification_report(y_test,ytree,output_dict=True)
print(treeacc)
print(treematrix)
print(treereport)

0.7217885024840313
[[849 186]
 [206 168]]
{'0': {'precision': 0.804739336492891, 'recall': 0.8202898550724638, 'f1-score': 0.8124401913875599, 'support': 1035.0}, '1': {'precision': 0.4745762711864407, 'recall': 0.44919786096256686, 'f1-score': 0.46153846153846156, 'support': 374.0}, 'accuracy': 0.7217885024840313, 'macro avg': {'precision': 0.6396578038396659, 'recall': 0.6347438580175153, 'f1-score': 0.6369893264630107, 'support': 1409.0}, 'weighted avg': {'precision': 0.7171020146869206, 'recall': 0.7217885024840313, 'f1-score': 0.7192980714701981, 'support': 1409.0}}


In [11]:
#Forest Model
forest=RandomForestClassifier()
forest.fit(X_train,y_train)
yforest=forest.predict(X_test)
forestacc=accuracy_score(yforest,y_test)
forestmatrix=confusion_matrix(y_test,yforest)
forestreport=classification_report(y_test,yforest,output_dict=True)
print(forestacc)
print(forestmatrix)
print(forestreport)

0.7650816181689141
[[922 113]
 [218 156]]
{'0': {'precision': 0.8087719298245614, 'recall': 0.8908212560386474, 'f1-score': 0.847816091954023, 'support': 1035.0}, '1': {'precision': 0.5799256505576208, 'recall': 0.41711229946524064, 'f1-score': 0.48522550544323484, 'support': 374.0}, 'accuracy': 0.7650816181689141, 'macro avg': {'precision': 0.6943487901910911, 'recall': 0.653966777751944, 'f1-score': 0.6665207986986289, 'support': 1409.0}, 'weighted avg': {'precision': 0.7480277790468213, 'recall': 0.7650816181689141, 'f1-score': 0.7515713230718123, 'support': 1409.0}}


In [13]:
metrics={
    "model":["pcaknn","pcasvc","pcaLogReg","pcaTree","pcaForest"],
    "precision":[knnreport["weighted avg"]["precision"],svcreport["weighted avg"]["precision"],logregreport["weighted avg"]["precision"],treereport["weighted avg"]["precision"],forestreport["weighted avg"]["precision"]],
    "recall":[knnreport["weighted avg"]["recall"],svcreport["weighted avg"]["recall"],logregreport["weighted avg"]["recall"],treereport["weighted avg"]["recall"],forestreport["weighted avg"]["recall"]],
    "f1":[knnreport["weighted avg"]['f1-score'],svcreport["weighted avg"]["f1-score"],logregreport["weighted avg"]["f1-score"],treereport["weighted avg"]["f1-score"],forestreport["weighted avg"]["f1-score"]]
}
metrics=pd.DataFrame(metrics)
metrics.head()

model  precision    recall        f1
0     pcaknn   0.760183  0.776437  0.762013
1     pcasvc   0.763511  0.779276  0.765035
2  pcaLogReg   0.748492  0.765791  0.751837
3    pcaTree   0.717102  0.721789  0.719298
4  pcaForest   0.748028  0.765082  0.751571

In [14]:
errors=pd.read_csv("Metrics.csv",index_col=0)
metrics=pd.concat([errors,metrics],ignore_index=True)
metrics

model  precision    recall        f1
0        baseknn   0.780759  0.792051  0.765596
1        basesvc   0.539584  0.734564  0.622155
2     baseLogReg   0.786733  0.794890  0.789405
3       baseTree   0.725576  0.723918  0.724729
4     baseForest   0.772494  0.786373  0.774088
5      normalknn   0.756183  0.772179  0.759077
6      normalsvc   0.781897  0.794180  0.783316
7   normalLogReg   0.780784  0.790632  0.783614
8     normalTree   0.724664  0.721789  0.723174
9   normalForest   0.769291  0.782115  0.772170
10        stdknn   0.761861  0.773598  0.765480
11        stdsvc   0.785510  0.797019  0.787104
12     stdLogReg   0.779081  0.788502  0.782020
13       stdTree   0.721343  0.719659  0.720483
14     stdForest   0.766697  0.780696  0.769265
15        pcaknn   0.760183  0.776437  0.762013
16        pcasvc   0.763511  0.779276  0.765035
17     pcaLogReg   0.748492  0.765791  0.751837
18       pcaTree   0.717102  0.721789  0.719298
19     pcaForest   0.748028  0.765082  0.751571

In [15]:
metrics.to_csv("metrics.csv")